# Generated by Django 2.2.3 on 2019-08-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chatters',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
